routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/dashboard', 'HomeController@index')->name('home')->middleware('auth');
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('table-list', 'MeetingController@index')->name('table');
    Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
    Route::get('passed_meetings', 'MeetingController@passedMeetings')->name('passed_meetings');
    Route::post('sendInvite', 'MeetingController@sendInvite')->name('sendInvite');
    Route::put('sendInvite', 'MeetingController@sendInvite')->name('sendInvite');

    Route::get('notifications', 'MeetingController@manageTasks')->name('notifications');
    Route::get('/meeting/{id}', 'MeetingController@show')->name('meeting.show');
    Route::get('editorg', 'MeetingController@editOrg')->name('editOrg');
    Route::put('editorg/{id}', 'MeetingController@updateOrg')->name('updateOrg');
});

Route::get('meetings/delete/{id}', 'MeetingController@destroy')->name('delete');
Route::get('meetings/addTopic/{id}', 'MeetingController@addTopic')->name('addTopic');
Route::get('meetings/Topic/{id}', 'MeetingController@createTopic')->name('createTopic');
Route::get('meetings/details/{id}', 'MeetingController@details')->name('details');
Route::get('meetings/deleteTask/{id}', 'MeetingController@deleteTask')->name('deleteTask');
// Route::get('moveTopics', 'MeetingController@moveTopics')->name('moveTopics');
Route::post('/meeting/{id}/moveTopics', 'MeetingController@moveTopics')->name('moveTopics');

Route::get('changeStatus', 'MeetingController@changeStatus');
Route::put('topics/{id}', 'MeetingController@changeTopicStatus');
Route::post('/meeting/{id}/tasks', 'MeetingController@createTask')->name('createTask');
Route::put('tasks/{id}', 'MeetingController@changeStatus');
Route::resource('meetings', 'MeetingController');
Route::post('meetings/store', 'MeetingController@store')->name('store');
Route::get('meetings/create', 'MeetingController@create')->name('create');


Route::get('editorg', 'MeetingController@editOrg')->name('editOrg');
Route::put('editorg/{id}', 'MeetingController@updateOrg')->name('updateOrg');

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-1.jpg">
  <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
  <div class="logo">
    <a href="https://www.jce.ac.il/" class="simple-text logo-normal">
      {{ __('JCE WEBSITE') }}
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('dashboard') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('Dashboard') }}</p>
        </a>
      </li>
      <li class="nav-item {{ ($activePage == 'profile' || $activePage == 'user-management') ? ' active' : '' }}">
        <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
        <i class="material-icons">account_box</i>
          <p>{{ __('Org & User') }}
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse show" id="laravelExample">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('profile.edit') }}">
              <i class="material-icons">face</i>
                <span class="sidebar-normal">{{ __('User profile') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('user.index') }}">
              <i class="material-icons">supervisor_account</i>
                <span class="sidebar-normal"> {{ __('Org Users') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('editOrg') }}">
              <i class="material-icons">list</i>
                <span class="sidebar-normal"> {{ __('Edit Organization') }} </span>
              </a>
            </li>
          </ul>
        </div>
      </li>
      <li class="nav-item{{ $activePage == 'table' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('table') }}">
          <i class="material-icons">content_paste</i>
            <p>{{ __('Meeting List') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'passed_meetings' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('passed_meetings') }}">
          <i class="material-icons">content_paste</i>
            <p>{{ __('Previous Meetings') }}</p>
        </a>
      </li>
      @cannot('participant')
      <li class="nav-item{{ $activePage == 'notifications' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('notifications') }}">
          <i class="material-icons">notifications</i>
            <p>{{ __('Manage Tasks') }}</p>
        </a>
      </li>
      @endcannot
    </ul>
  </div>
</div>