routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/dashboard', 'HomeController@index')->name('home')->middleware('auth');
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('table-list', 'MeetingController@index')->name('table');
    Route::get('/dashboard', 'MeetingController@dashboard')->name('dashboard');
    Route::get('passed_meetings', 'MeetingController@passedMeetings')->name('passed_meetings');
    Route::post('sendInvite', 'MeetingController@sendInvite')->name('sendInvite');
    Route::put('sendInvite', 'MeetingController@sendInvite')->name('sendInvite');

    Route::get('notifications', 'MeetingController@manageTasks')->name('notifications');
    Route::get('/meeting/{id}', 'MeetingController@show')->name('meeting.show');
    Route::get('editorg', 'MeetingController@editOrg')->name('editOrg');
    Route::put('editorg/{id}', 'MeetingController@updateOrg')->name('updateOrg');
});

Route::get('meetings/delete/{id}', 'MeetingController@destroy')->name('delete');
Route::get('meetings/addTopic/{id}', 'MeetingController@addTopic')->name('addTopic');
Route::get('meetings/Topic/{id}', 'MeetingController@createTopic')->name('createTopic');
Route::get('meetings/details/{id}', 'MeetingController@details')->name('details');
Route::get('meetings/deleteTask/{id}', 'MeetingController@deleteTask')->name('deleteTask');
// Route::get('moveTopics', 'MeetingController@moveTopics')->name('moveTopics');
Route::post('/meeting/{id}/moveTopics', 'MeetingController@moveTopics')->name('moveTopics');

Route::get('changeStatus', 'MeetingController@changeStatus');
Route::put('topics/{id}', 'MeetingController@changeTopicStatus');
Route::post('/meeting/{id}/tasks', 'MeetingController@createTask')->name('createTask');
Route::put('tasks/{id}', 'MeetingController@changeStatus');
Route::resource('meetings', 'MeetingController');
Route::post('meetings/store', 'MeetingController@store')->name('store');
Route::get('meetings/create', 'MeetingController@create')->name('create');


Route::get('editorg', 'MeetingController@editOrg')->name('editOrg');
Route::put('editorg/{id}', 'MeetingController@updateOrg')->name('updateOrg');

resources/views/pages/details.blade.php
@extends('layouts.app', ['activePage' => 'details', 'titlePage' => __('Details Meeting')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">My Meetings</h4>
            <p class="card-category"> Previous Meetings</p>
            <div class="row">

                </div>
          </div>
          <div class="card-body">
          <h5 style="font-weight: bold;"> The details of the meeting </h5>
          
          <ul>
          <div class="col-10 text-right">
            </div>
            <li> Meeting Title : {{$meeting->title}} </li>
            <li> Location : {{$meeting->location}} </li>
            <li> Date & Time : {{$meeting->date}} </li>
            <li> Length : {{$meeting->length}} hours </li> 
            <li> Topics :</li>
            <ul>
            @foreach($topics as $topic)
            @if($topic->meeting_id==$meeting->id)
            <li> {{$topic->title}} </li>
            @endif
            @endforeach
            </ul>
            <li> Task :</li>
            <ul>
            @foreach($tasks as $task)
            @if($task->meeting_id==$meeting->id)
            <li> {{$task->title}} - 
            @if($task->status == 0) 
            Not Done
            @else
            Done 
            @endif
            </li>
            @endif
            @endforeach
            </ul>
            <li> Invites :</li>
            <ul>
            @foreach($invites as $invite)
            @if($invite->meeting_id==$meeting->id)
            <li> {{$invite->user->name}} </li>
            @endif
            @endforeach
            </ul>

            </ul>
            </div>
        </div> 
        
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pages/icons.blade.php
@extends('layouts.app', ['activePage' => 'icons', 'titlePage' => __('Icons')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="container-fluid">
      <div class="card card-plain">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Material Design Icons</h4>
          <p class="card-category">Handcrafted by our friends from
            <a target="_blank" href="https://design.google.com/icons/">Google</a>
          </p>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card-body">
              <div class="iframe-container d-none d-lg-block">
                <iframe src="https://design.google.com/icons/">
                  <p>Your browser does not support iframes.</p>
                </iframe>
              </div>
              <div class="col-md-12 d-none d-sm-block d-md-block d-lg-none d-block d-sm-none text-center ml-auto mr-auto">
                <h5>The icons are visible on Desktop mode inside an iframe. Since the iframe is not working on Mobile and Tablets please visit the icons on their original page on Google. Check the
                  <a href="https://design.google.com/icons/" target="_blank">Material Icons</a>
                </h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pages/map.blade.php
@extends('layouts.app', ['activePage' => 'map', 'titlePage' => __('Map')])

@section('content')
@endsection

resources/views/pages/meeting_list.blade.php
@extends('layouts.app', ['activePage' => 'table', 'titlePage' => __('Meeting List')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">My Meetings</h4>
            <p class="card-category"> Upcoming Meetings</p>
            <div class="row">

                </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
              @cannot('participant')  
              <div class="col-12 text-right">
                    <a href="{{ route('create') }}" class="btn btn-sm btn-primary">{{ __('Create a new meeting') }}</a>
              </div>
              @endcannot
        <tr>
            <th scope="col">#</th>
            <th scope="col">Meeting Title</th>
            <th scope="col">Location</th>
            <th scope="col">Date & Time</th>
            <th scope="col">Length</th>
            <th scope="col" class="th-actions text-right"></th>
            <th scope="col" class="th-actions text-right">Actions</th>


        </tr>
        <tbody>
        @foreach($meetings as $meeting)
            <tr>
                <th scope="row">{{$meeting->id}}</th>
                <td>{{$meeting->title}}</td>
                <td>{{$meeting->location}}</td>
                <td>{{$meeting->date}}</td>
                <td>{{$meeting->length}} hours</td>
                <td class="td-actions"><a href="https://www.google.com/calendar/render?action=TEMPLATE&text={{urlencode($meeting->title)}}&dates={{$meeting->date->format('Ymd\THis\Z')}}/{{$meeting->date->addHours($meeting->length)->format('Ymd\THis\Z')}}&details=For+details,+link+here:+http://www.example.com&location={{urlencode($meeting->location)}}&sf=true&output=xml" target="_blank" class="btn btn-sm btn-info">{{ __('Sync with Google Calendar') }}</a></td>

                @if($meeting->creator_id == Auth::user()->id)
                <td class="td-actions text-right"><a href="{{route('meeting.show',$meeting->id)}}" class="btn btn-sm btn-success">{{ __('Start the Meeting') }}</a></td>

                <td class="td-actions text-right">
                              <form action="" method="post">
                                  @csrf
                                  @method('delete')
                              
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{route('meetings.edit', $meeting->id)}}" >
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <a rel="tooltip" class="btn btn-danger btn-link" href="{{route('delete', $meeting->id)}}" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this?") }}') ? this.parentElement.submit() : ''">
                                    <i class="material-icons">close</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <meta name="csrf-token" content="{{ csrf_token() }}">
    
                              </form>
                            
                          </td>
              @else
              @can('manager') 
              <td class="td-actions text-right"><a href="{{route('meeting.show',$meeting->id)}}" class="btn btn-sm btn-success">{{ __('Start the Meeting') }}</a></td>

                <td class="td-actions text-right">
                              <form action="" method="post">
                                  @csrf
                                  @method('delete')
                              
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{route('meetings.edit', $meeting->id)}}" >
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <a rel="tooltip" class="btn btn-danger btn-link" href="{{route('delete', $meeting->id)}}" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this?") }}') ? this.parentElement.submit() : ''">
                                    <i class="material-icons">close</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <meta name="csrf-token" content="{{ csrf_token() }}">
    
                              </form>
                            
                          </td>
              @endcan
              @endif

            </tr>
        @endforeach
        </tbody>
    </table>
           
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/pages/notifications.blade.php
@extends('layouts.app', ['activePage' => 'notifications', 'titlePage' => __('Notifications')])

@section('content')

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Manage Tasks</h4>
            <p class="card-category"> that have been created by you</p>
            <div class="row">

                </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
        <tr>
        <th></th>
             <th scope="col" width='80'>Meeting</th>
             <th width='100'></th>
            <th scope="col">Task Title</th>
            <th scope="col">Due Date</th>
            <th scope="col">Assigned To</th>
            <th scope="col">Status</th>
            <th scope="col" class="td-actions text-right">Delete</th>

        </tr>
        <tbody>
        @foreach($tasks as $task)
          @if($task->creator_id==Auth::user()->id)
            <tr>
            <td>
            
                <td>{{$task->meeting_id}}</td>
                
                @if($task->status == 0 && $task->due_date < $dt)
                <td class='text-right'><img src="http://localhost/planner/public/material/img/delayed.jpg" height="40" width="80" class="css-class" alt="alt text"></td></td>
                @elseif($task->status == 1 && $task->due_date < $task->updated_at)
                <td class='text-right'><img src="http://localhost/planner/public/material/img/delayed.jpg" height="40" width="80" class="css-class" alt="alt text"></td></td> 
                @elseif($task->status == 1)
                <td class='text-right'><img src="http://localhost/planner/public/material/img/completed.png" height="40" width="80" class="css-class" alt="alt text"></td>
                @else
                <td></td>
                @endif
                <th scope="row"> {{$task->title}}</th>
                <td>{{$task->due_date}}</td>
                <td>{{$task->user->name}}</td>
                @if($task->status == 1)
                <td>Done</td>
                @else 
                <td>Not done</td>
                @endif
                <td class="td-actions text-right">
                              <form action="" method="post">
                                  @csrf
                                  @method('delete')
                              

                                  <a rel="tooltip" class="btn btn-danger btn-link" href="{{route('deleteTask', $task->id)}}" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this?") }}') ? this.parentElement.submit() : ''">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                  </button>
                              </form>
                            
                          </td>
            </tr>
        @endif
        @endforeach
        </tbody>
    </table>
           
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/pages/passed_meetings.blade.php
@extends('layouts.app', ['activePage' => 'passed_meetings', 'titlePage' => __('Meeting List')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">My Meetings</h4>
            <p class="card-category"> Previous Meetings</p>
            <div class="row">

                </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
              <div class="col-12 text-right">
                  </div>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Meeting Title</th>
            <th scope="col">Location</th>
            <th scope="col">Date & Time</th>
            <th scope="col">Length</th>

        </tr>
        <tbody>
        @foreach($meetings as $meeting)
            <tr>
                <th scope="row">{{$meeting->id}}</th>
                <td><a href="{{route('details', $meeting->id)}}">{{$meeting->title}}</a></td>
                <td>{{$meeting->location}}</td>
                <td>{{$meeting->date}}</td>
                <td>{{$meeting->length}} hours</td>

               
            </tr>
        @endforeach
        </tbody>
    </table>
           
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pages/upgrade.blade.php
@extends('layouts.app', ['activePage' => 'upgade', 'titlePage' => __('Upgrade to PRO')])

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Material Dashboard PRO</h4>
            <p class="card-category">Are you looking for more components? Please check our Premium Version of Material Dashboard.</p>
          </div>
          <div class="card-body">
            <div class="table-responsive table-upgrade">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th class="text-center">Free</th>
                    <th class="text-center">PRO</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><h3 class="text-primary">Laravel</h3></td>
                    <td class="text-center"></td>
                    <td class="text-center"></td>
                  </tr>
                  <tr>
                    <td>Login, Register, Forgot password pages</td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>User profile</td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Users management</td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>User roles management </td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Items management </td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Categories management, Tags management </td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Wysiwyg, image upload, date picker inputs</td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Radio button, checkbox, toggle inputs</td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td><h3 class="text-primary">Frontend</h3></td>
                    <td class="text-center"></td>
                    <td class="text-center"></td>
                  </tr>
                  <tr>
                    <td>Components</td>
                    <td class="text-center">60</td>
                    <td class="text-center">200</td>
                  </tr>
                  <tr>
                    <td>Plugins</td>
                    <td class="text-center">2</td>
                    <td class="text-center">15</td>
                  </tr>
                  <tr>
                    <td>Example Pages</td>
                    <td class="text-center">3</td>
                    <td class="text-center">27</td>
                  </tr>
                  <tr>
                    <td>Login, Register, Pricing, Lock Pages</td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>DataTables, VectorMap, SweetAlert, Wizard, jQueryValidation, FullCalendar etc...</td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td>Mini Sidebar</td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td><h3 class="text-primary">Premium Support</h3></td>
                    <td class="text-center"><i class="fa fa-times text-danger"></i></td>
                    <td class="text-center"><i class="fa fa-check text-success"></i></td>
                  </tr>
                  <tr>
                    <td></td>
                    <td class="text-center">Free</td>
                    <td class="text-center">Just $149</td>
                  </tr>
                  <tr>
                    <td class="text-center"></td>
                    <td class="text-center">
                      <a href="#" class="btn btn-round btn-fill btn-default disabled">Current Version</a>
                    </td>
                    <td class="text-center">
                      <a target="_blank" href="https://www.creative-tim.com/product/material-dashboard-pro-laravel" aria-disabled="true" class="btn btn-round btn-fill btn-info">Upgrade to PRO</a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection